### PR TITLE
Build hardware drivers with VNDK enabled

### PR DESCRIPTION
**Pull request by Quallenauge**
Although it's not clear if the SOC is able to boot into a VNDK in future, but
I'd like the idea that we are ready for it, at least for our hw drivers.

### CODE REVIEW

**Comment by vladimiroltean** [comment]
The commit message for `wcnss: Build libgnss with the VNDK.` is incorrect. You were referring to `libwcnss_qmi`.
It would be nice if you could pick up the additional patches in this pull request: https://github.com/Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common/pull/29 and integrate them into yours when resending, so that we can merge.

**Comment by vladimiroltean** [comment]
To build a full image with the VNDK enabled, you also need these 2 patchsets:

* https://review.lineageos.org/#/c/LineageOS/android_hardware_qcom_audio/+/220562/
* https://review.lineageos.org/#/c/LineageOS/android_hardware_qcom_media/+/220567/

As discussed, currently the blocker is the hwcomposer HAL, which has non-trivial dependencies on system libraries libskia and libmedia.

**Comment by vladimiroltean** [comment]
Diff statistics:  +43 −19,384
If the code is really unused, why does it cause compilation issues with VNDK enabled?

**Review by vladimiroltean — COMMENTED** [review]
Are you sure it's really true that .mk is used instead of .bp, if both are present? Also, what prompted you to remove it?

**Review by vladimiroltean — COMMENTED** [review]
I think this is a bit overreaching. I agree the code quality is under the sea level, but if it really is unused (and I don't see anything removed from `PRODUCT_PACKAGES`) I don't see why it'd break while compiling with the VNDK.
I don't disagree with removing it, just that I find the VNDK pretext a bit strange, if I understand things correctly.

**Comment by Quallenauge** [comment]
Camera test application code: Maybe we can let the test code in our repo, but I don't think the modules are needed for a common build. That's why compilation issues (not only VNDK related doesn't appears).
When I tried to compile with `mm`, which compiled all components at the folder, I got some errors, which I was not able to solve (easily). I might be wrong, but it seems that the code wasn't maintained for a long time. So my approach was to remove these components, because they are available also at the CAF upstream code. 

Do you think we should let them in as reference implementation which is not used but to complete the camera repo package ? Or I have to remove the code with a separate commit.

Android.bp: That's the next big thing to convert all of the mk files to bp files :) I have to admit, I'm lacking experience at this field...
So here I concentrated to the *.mk files.

**Comment by Quallenauge** [comment]
Would it be better to remove the two commits in question?!

**Comment by vladimiroltean** [comment]
I would keep the patchset as minimal as possible for VNDK purposes. In this context, maybe a test with `mm` is irrelevant.

**Comment by Quallenauge** [comment]
I removed the two commits and re-pushed.

**Review by vladimiroltean — APPROVED** [review]

**Pull request merged**
