### PR TITLE
Enable mm-pp-daemon.

### PR DESCRIPTION
**Pull request by Quallenauge**
The mm-pp-daemon is responsible for setting color settings
and cabl as well. There is an pp_calib_data file needed to
get the color temperature feature working. The one within
this commit is taken from
pp_calib_data_sharp_r63315_1080p_video_mode_dsi_panel.xml
and has to be adapted for the current display with appropriate
values. As start it seems to give good results.

The shims are extended to load libdisplayconfig.so when loading
the libqdutils.so. This is needed due a recent change, where the
refreshScreen() function was moved to a dedicated library. To solve
the issue, load the libdisplayconfig to let these functions be visible
to dlsym().

Enable CABL by setting appropriate arguments to the mm-pp-daemon.
This has to be reverted in future and replaced by a proper implementation
of a derrived device specific LiveDisplayMM controller.
Also the system property is set to ro.qualcomm.cabl=2 which maches the stock
values.

Change-Id: I81c3884fa15a1f65f74427feb4ccbadc6e394faa

### CODE REVIEW

**Comment by Gabriel85** [comment]
What do you mean with "colour temperature feature"?
About CABL: please split the patch. I don't see that CABL support is anything, which will be ever supported. I've looked into it, and I decided not to waste my time with it. Implementing it is a mess and it seems there is 0 demand for it. Unless of course you are implementing it by yourself...

**Comment by Quallenauge** [comment]
Added two PR's to make use of the CABL function of mm-pp-daemon:

[220840 livedisplay: Enable cabl via mm-pp-daemon.](https://review.lineageos.org/#/c/LineageOS/android_hardware_lineage_interfaces/+/220840/)
[220841 livedisplay: Query active state via native call.](https://review.lineageos.org/#/c/LineageOS/android_hardware_lineage_interfaces/+/220841/)

**Comment by Gabriel85** [comment]
Whats the point if that, if CABL isn't working, and nobody intents to make it work anyways? Cherry-picking some commits is one thing, implementing the low-level hardware hack is a completely different story. I would recommend not merging anything CABL related before it is actually working.. ;)

**Comment by Quallenauge** [comment]
Gabriel, please inform before you write. It seems to me you didn't looked into this thing.
And also IF it isn't working, why not providing a PR for everyone. Maybe someone has a good idea.

**Comment by Gabriel85** [comment]
It can't work, because the kernel doesn't support it! Doesn't look that this will change anytime soon, and probably doesn't need to. Or do you want to implement it properly in the kernel?

**Comment by Quallenauge** [comment]
Please point me to the correct location within the kernel where the CABL has to be implemented, so I can understand.

**Comment by Gabriel85** [comment]
Wherever you want. It just needs to compatible to what LOS Liveview expects.

**Comment by vladimiroltean** [comment]
What is LOS Liveview?
I don't understand either. An example might help.

**Comment by Gabriel85** [comment]
I meant LiveDisplay, or however LOS calls their display settings. I doubt they keep that stuff anyways in the long run, since AOSP also supports changing the Display colour and this has nothing to do with changing hardware display function.

**Comment by Gabriel85** [comment]
I don't really get what this stuff has to do with CABL at all. Isn't this about changing the colour calibration?

And concerning "ro.qualcomm.cabl": is this value also in the stock ROM? "Qualcomm CABL" is an older software implementation, which has nothing to do with the hardware implementation of our panel.  I'm not sure if our SOC even supports it, and it would need some additional QC blobs.

And another thing: not all tablets use a Sharp panel! Some have a compatible one from another vendor. So maybe they are differently calibrated..

**Comment by Quallenauge** [comment]
> And concerning "ro.qualcomm.cabl": is this value also in the stock ROM?

You can find that out easily by looking at the build.prop.

> Qualcomm CABL" is an older software implementation, which has nothing to do with the hardware implementation of our panel. I'm not sure if our SOC even supports it, and it would need some additional QC blobs.

Can you please go more into the detail of this daemon? I want technical infos to understand that component in the right manner. I admit I have to learn much about this thing.

>"Qualcomm CABL" is an older software implementation, which has nothing to do with the hardware implementation of our panel.

I think it has nothing to do with the CABC (automatic panel and backlight adjustments).

>I'm not sure if our SOC even supports it, and it would need some additional QC blobs.

What is the SOC dependency to use it? Which blobs are needed?

The questions/statements here are so vague, I must admit it causes more questions than answers.

**Comment by Gabriel85** [comment]
I don't know how the stock build.prop looks like. But I doubt stock uses "CABL" and "CABC", since both do basically the same. I guess software CABL was used before panels supported it in hardware. I just know that QC CABL needs several blobs, configuration files and comes with an APK for changing it's settings. But that thing seems to be out of use for many years now, and I can't remember seeing anything of that in the stock ROM or kernel.
I guess those setting comes from another device and should be removed. Therefore, the LiveDisplay implementation of CABC is enough.

**Comment by Quallenauge** [comment]
Thanks for the ketchup. But where is the real info?

**Comment by Gabriel85** [comment]
Right before your nose: https://github.com/Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common/commit/764d31657f9a3cf3113d152397f10b572c2bfd08

Christian added it, probably because he thought he could disable CABC with it, and never removed it again. Also it is logical, since the setting is called ro.QUALCOMM.cabl, and you should already have found out by yourself, that our CABC is independent of the SOC.

**Comment by Quallenauge** [comment]
So then check the build.prop of stock rom image and you also can smell what is set in the stock build.

**Comment by Gabriel85** [comment]
I don't have it, that's your turf.. But even if it's in there, still probably is a leftover from another device. Or does changing the setting has any effect? ;)
Also I can't find anything which suggest that this is used by any current QC SOC.

**Comment by Quallenauge** [comment]
> I don't have it, that's your turf..  

I miss some own responsibility here. And that costs time for everyone.
Please keep in mind, I don't have to do anything what I don't want for this "project".
And I get the feeling of that attitude of the previous posts.

**Last answer from me until no valuable info comes in.**

**Comment by Gabriel85** [comment]
https://github.com/LineageOS/android_hardware_qcom_display/search?q=CablProp&unscoped_q=CablProp

It only was supported on MSM8960, which was released in 2012...
No other SOC even reads this property. Evidence enough?

**Comment by Quallenauge** [comment]
Just a hint for the future: Not all things are visible in open source files.

**Comment by Gabriel85** [comment]
Is the setting doing anything? Yes or no.. 
But given the useless back and forth, without you being able to answer this simple question, it's probably not.. ;)

**Comment by Quallenauge** [comment]
Welcome in the club (of vague speaking only).

**Pull request closed without merging**
