### PR TITLE
[CM14] sepolicy: add back rules for the Dolby Atmos addon

### PR DESCRIPTION
**Pull request by vladimiroltean**
* According to the instructions in the system/sepolicy/README file for
  insertkeys.py, a working way to define a selinux domain for a
  presigned app (Ax.apk) is:

```
  $ java -jar ~/bin/apktool-2.3.2-SNAPSHOT-small.jar decode
    system/vendor/app/Ax/Ax.apk --output dolby
  $ openssl pkcs7 -in dolby/original/META-INF/CERT.RSA -inform der -print_certs
  # Then import that public key into a base64 to base16 converter, such
  # as https://holtstrom.com/michael/tools/hextopem.php, and save the
  # result in mac_permissions.xml.
  # A SELinux domain for applications signed with the above key can now
  # be defined in seapp_contexts.
```

* Current Dolby addon is Dolby-YTX703-v23 and can be found at
  https://github.com/Lenovo-YTX703-Devel/lenovo_YTX703_TWRP_zips

Change-Id: I5e4e5248954cf23e48a43bbe0654abab0edbff04
Authored-by: Matthias Lenk <matthias.lenk@gmx.de>
Signed-off-by: Vladimir Oltean <olteanv@gmail.com>

### CODE REVIEW

**Comment by vladimiroltean** [comment]
Applicable to cm14 only.

**Comment by vladimiroltean** [comment]
FYI, compare to:
https://github.com/Lenovo-YTX703-Devel/android_device_lenovo_YTX703-common/commit/f99e9c7fc8f837a948df8a86e2f699aea516a61a

**Comment by Quallenauge** [comment]
Here it would be nice if @Gabriel85 could look at it. From my side it looks good, but I'm not sure without tests.

**Comment by Gabriel85** [comment]
Vlad's solution is undoubtedly nice than mine, but I already wrote a even more elegant one. But I would prefer to remove that Dolby stuff for now form this repo, since the zip itself is originally created by a script and properly signed by it. If you repack this one, the signing won't be valid anymore, since it contains the wrong keys. 
Therefore, I'd like to make a separate repo, including my script and the java program used for signing it. So everybody can build a proper zip  by yourself.

**Comment by Quallenauge** [comment]
There are the correct blobs attached within the [lenovo_YTX703_TWRP_zips](https://github.com/Lenovo-YTX703-Devel/lenovo_YTX703_TWRP_zips) repo. The APK keys should match at least for this build for the provided packages. So if the intention is to provide a complete cm14.1 build, I think this is reasonable.

If a new TWRP Dolby Zip is available, we are able to update `sepolicy/mac_permissions.xml`.

**Comment by Gabriel85** [comment]
Sorry, I don't mean this key, I mean the one which the dolby installation zip is signed with:
https://github.com/Lenovo-YTX703-Devel/lenovo_YTX703_TWRP_zips/blob/master/Dolby-YTX703-v23/META-INF/com/android/otacert

**Comment by Gabriel85** [comment]
My fault! I thought I was commenting the other request in the other repo with the zips.. :innocent:
I think we should wait a couple of days before we merge this, since the rules are quite drastically reduced. But Vlad already tested them extensively, so I guess they are fine! :smiley:

**Pull request merged**
